### ISSUE TITLE
There are already social-networks, do something else

### ISSUE THREAD

**Issue by andrerpena** [danielschmitz/social-network#1]
Consider doing something else

**Comment by danielschmitz** [comment]
its 4 my new book ;-)

**Comment by andrerpena** [comment]
I was just kidding. Good luck on the upcoming book.

On Saturday, 23 April 2016, Daniel Schmitz <notifications@github.com> wrote:

> Closed #1 <https://github.com/danielschmitz/social-network/issues/1>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/danielschmitz/social-network/issues/1#event-638574972>
>


-- 
André Rodrigues Pena
